reviewers:
  defaults:
    - rollkit
  groups:
    rollkit:
      - team:core
files:
  ".github/**":
    - rollkit
options:
  ignore_draft: true
  ignored_keywords:
    - WIP
  number_of_reviewers: 3
